---
title: "A Sufficient Statistics Approach to Ex Ante Health Policy Evaluation"
author: "John A. Graves"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE
)
# Load packages and source functions. 
source(here::here("R/manifest.R"))
```

```{r,child="./R/introduction.Rmd"}
```


<!-- As an example, I  apply VOI methos to reduced form evidence on the MVPF  willingness to pay (WTP) for subsidized health insurance, which i -->

<!-- I show how VOI methods can fileter uncertainty in RD paramters from Finkelstein , as well as assumptions  -->


<!-- That is, VOI methdos can be used to quantify the opportunity cost of a "wrong" decision. In that way, we can identify and prioritize research and modeling efforts on the parameters and/or assumptions that drive uncertainty. To demonstrate the power of VOI -->



<!-- ### Estimating the Transition Probability Matrix -->

<!-- We first obtain a simple cross tabulation of insurance coverage in January 2013 from the SIPP.  -->

<!-- ```{r, echo = FALSE} -->
<!-- # source(here("R/estimate-overall-transition-probability-matrix.R")) -->
<!-- ex_ante <-  -->
<!--   read_rds(here("output/ex-ante-overall-population/ex-ante-distribution.rds")) -->
<!-- ex_ante_meps <-  -->
<!--   read_rds(here("output/ex-ante-overall-population/ex-ante-distribution-meps.rds")) -->

<!-- ex_ante %>%  -->
<!--   mutate(n = round(n/1e6,1)) %>%  -->
<!--   mutate(pct = round(100*pct,1)) %>%  -->
<!--   mutate(insurance_type = c("ESI","Private-Other","Public","Uninsured")) %>%  -->
<!--   cbind( -->
<!--     ex_ante_meps %>%  -->
<!--     mutate(n = round(n/1e6,1)) %>%  -->
<!--     mutate(pct = round(100*pct,1)) %>%  -->
<!--     select(-insurance_type)  -->
<!--   ) %>%  -->
<!--   knitr::kable(caption = "Ex Ante Distribution of Insurance Coverage, January 2013",col.names= c("Category","SIPP: Number (millions)","SIPP: Percent", "MEPS: Number (millions)","MEPS: Percent"), format = "html") -->
<!-- ``` -->

<!-- Next we fit nonpaarametric (Kaplan-Meier) and parametric multi-state models to obtain the transition probabilities by December 2013.  -->

<!-- ```{r} -->
<!-- trans_probs <-  -->
<!--     read_rds(here("output/ex-ante-overall-population/transition-probabilities-kaplan-meier.rds")) -->

<!-- trans_probs %>% filter(time==24) %>% pluck("data") %>% pluck(1) %>%  -->
<!--   mutate_at(vars(-1),function(x) round(100*x,2)) %>%  -->
<!--   knitr::kable(caption = "Transition Probabilities", format = "html") -->
<!-- ``` -->

<!-- ```{r} -->
<!--  trans_probs_meps <-  -->
<!--     read_rds(here("output/ex-ante-overall-population/transition-probabilities-kaplan-meier-meps.rds")) -->

<!-- trans_probs_meps %>% filter(time==24) %>% pluck("data") %>% pluck(1) %>%  -->
<!--   mutate_at(vars(-1),function(x) round(100*x,2)) %>%  -->
<!--   knitr::kable(caption = "Transition Probabilities", format = "html") -->
<!-- ``` -->

