options("scipen"=100, "digits"=6)
library(tidyverse)
library(rlang)
library(kableExtra)
library(knitr)
library(pander)
library(magrittr)
library(doParallel)
library(mstate)
library(flexsurv)
library(eha)
library(heemod)
library(here)
library(conflicted)
library(cluster)
library(directlabels)
library(gt)
library(patchwork)
library(randtoolbox)
library(matrixStats)  
library(mgcv) 

conflict_prefer("filter", "dplyr")
conflict_prefer("set_names", "rlang")
conflict_prefer("lag", "dplyr")
conflict_prefer("set_names","rlang")
conflict_prefer("filter","dplyr")
conflict_prefer("count","dplyr")

source(here::here("R/prepare-multistate-data.R"))
source(here::here("R/fit-multistate-model.R"))
source(here::here("R/get-cumulative-hazard.R"))
source(here::here("R/add-binary-indicators.R"))


source(here::here("../../../box/sccs-r01/transitions-dd/R//prepare-multistate-data.R"))
source(here::here("../../../box/sccs-r01/transitions-dd/R//fit-multistate-model.R"))
source(here::here("../../../box/sccs-r01/transitions-dd/R//get-cumulative-hazard.R"))
source(here::here("../../../box/sccs-r01/transitions-dd/R//add-binary-indicators.R"))
source(here::here("../../../box/sccs-r01/transitions-dd/R//transitions-dd-model.R"))
source(here::here("../../../box/sccs-r01/transitions-dd/R//ri-permute.R"))
source(here("./R/functions_finkelstein-hendren-shepard-replication.R"))
source(here("./R/functions-simulation.R"))
source(here::here("R/shared-objects.R"))

