options("scipen"=100, "digits"=6)
library(tidyverse)
library(rlang)
library(kableExtra)
library(knitr)
library(pander)
library(magrittr)
library(doParallel)
library(mstate)
library(flexsurv)
library(eha)
library(heemod)
library(here)
library(conflicted)
library(cluster)
conflict_prefer("filter", "dplyr")
conflict_prefer("set_names", "rlang")
conflict_prefer("lag", "dplyr")